### ISSUE TITLE
你是作者么？

### ISSUE THREAD

**Issue by wcx929** [AkkoSpace/Nokia-No-Ghosts#1]
还是说你也是扒的别人的？

**Comment by LvFinch** [comment]
您好，我的代码是在学习web前端期间遇到的一个很有意思的网站中的一个小功能，这个仓库是我本人学习网站作者的代码之后，自己组织整理学习用的，其中的主要代码非被人所写，如果你仅是学习遵照MIT协议是完全可以的。
